package bany.events.repositories.impl;

import bany.events.dtos.request.EventRequest;
import bany.events.dtos.response.EventResponse;
import bany.events.exceptions.ResoruceNotFoundException;
import bany.events.mappers.EventMapper;
import bany.events.models.Event;
import bany.events.repositories.interfaces.EventRepository;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

@Repository
public class EventMemoryRepositoryImpl implements EventRepository {

    private final List<Event> events = new ArrayList<>();
    private final AtomicLong idGenerator = new AtomicLong(1);

    @Override
    public EventResponse save(EventRequest eventDto) {
        //change dto to model
        Event event = EventMapper.EVENTMAPPER.toEntity(eventDto);
        // set id generated by atomic
        event.setId(idGenerator.get());
        // add event to memory data
        events.add(event);

        return EventMapper.EVENTMAPPER.toResponseDto(event);
    }

    @Override
    public List<EventResponse> findAll() {
        return events.stream().map(EventMapper.EVENTMAPPER::toResponseDto).toList();
    }

    @Override
    public Optional<EventResponse> findById(Long id) {
        return events.stream().filter(event -> event.getId().equals(id))
                .findFirst()
                .map(EventMapper.EVENTMAPPER::toResponseDto);
    }

    @Override
    public EventResponse update(EventRequest event) {
        return null;
    }

    @Override
    public void delete(Long id) {

        if(findById(id).isEmpty()){
            throw new ResoruceNotFoundException("Event", id);
        }

        events.removeIf(event -> event.getId().equals(id));
    }


}
