package bany.events.repositories.impl;

import bany.events.dtos.request.EventRequest;
import bany.events.dtos.response.EventResponse;
import bany.events.exceptions.ResourceNotFoundException;
import bany.events.mappers.EventMapper;
import bany.events.models.Event;
import bany.events.repositories.interfaces.EventRepository;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

@Repository
public class EventMemoryRepositoryImpl implements EventRepository {

    private final List<Event> events = new ArrayList<>();
    private final AtomicLong idGenerator = new AtomicLong(1);

    @Override
    public EventResponse save(EventRequest eventDto) {
        //change dto to model
        Event event = EventMapper.EVENT_INSTANCE.toEntity(eventDto);
        // set id generated by atomic
        event.setId(idGenerator.getAndIncrement());
        // add event to memory data
        events.add(event);

        return EventMapper.EVENT_INSTANCE.toResponseDto(event);
    }

    @Override
    public List<EventResponse> findAll() {
        return events.stream().map(EventMapper.EVENT_INSTANCE::toResponseDto).toList();
    }

    @Override
    public Optional<EventResponse> findById(Long id) {
        return events.stream().filter(event -> event.getId().equals(id))
                .findFirst()
                .map(EventMapper.EVENT_INSTANCE::toResponseDto);
    }

    @Override
    public EventResponse update(Long id,EventRequest eventDto) {
        Optional<Event> eventOptional = events.stream()
                .filter(event -> event.getId().equals(id))
                .findFirst();

        if (eventOptional.isEmpty()) {
            throw new ResourceNotFoundException("Event", id);
        }
        Event updatedEvent = EventMapper.EVENT_INSTANCE.toEntity(eventDto);
        updatedEvent.setId(id);

        events.removeIf(e -> e.getId().equals(id));
        events.add(updatedEvent);
        return EventMapper.EVENT_INSTANCE.toResponseDto(updatedEvent);
    }

    @Override
    public void delete(Long id) {

        //validate if event id exists
        if(findById(id).isEmpty()){
            throw new ResourceNotFoundException("Event", id);
        }
        events.removeIf(event -> event.getId().equals(id));
        idGenerator.getAndDecrement();
    }


}
