package bany.events.repositories.impl;

import bany.events.dtos.request.EventFilterRequest;
import bany.events.dtos.request.EventRequest;
import bany.events.dtos.response.EventResponse;
import bany.events.dtos.response.PageResponse;
import bany.events.exceptions.ResourceNotFoundException;
import bany.events.mappers.EventMapper;
import bany.events.entities.EventEntity;
import bany.events.repositories.interfaces.EventRepository;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

@Repository
@Profile("memory")
public class EventMemoryRepositoryImpl implements EventRepository {

    private final List<EventEntity> eventEntities = new ArrayList<>();
    private final AtomicLong idGenerator = new AtomicLong(1);

    @Override
    public EventResponse save(EventRequest eventDto) {
        //change dto to model
        EventEntity eventEntity = EventMapper.EVENT_INSTANCE.toEntity(eventDto);
        // set id generated by atomic
        eventEntity.setId(idGenerator.getAndIncrement());
        // add event to memory data
        eventEntities.add(eventEntity);

        return EventMapper.EVENT_INSTANCE.toResponseDto(eventEntity);
    }

    @Override
    public List<EventResponse> findAll() {
        return eventEntities.stream().map(EventMapper.EVENT_INSTANCE::toResponseDto).toList();
    }

    @Override
    public Optional<EventResponse> findById(Long id) {
        return eventEntities.stream().filter(event -> event.getId().equals(id))
                .findFirst()
                .map(EventMapper.EVENT_INSTANCE::toResponseDto);
    }

    @Override
    public EventResponse update(Long id,EventRequest eventDto) {
        Optional<EventEntity> eventOptional = eventEntities.stream()
                .filter(event -> event.getId().equals(id))
                .findFirst();

        if (eventOptional.isEmpty()) {
            throw new ResourceNotFoundException("Event", id);
        }
        EventEntity updatedEventEntity = EventMapper.EVENT_INSTANCE.toEntity(eventDto);
        updatedEventEntity.setId(id);

        eventEntities.removeIf(e -> e.getId().equals(id));
        eventEntities.add(updatedEventEntity);
        return EventMapper.EVENT_INSTANCE.toResponseDto(updatedEventEntity);
    }

    @Override
    public void delete(Long id) {

        //validate if event id exists
        if(findById(id).isEmpty()){
            throw new ResourceNotFoundException("Event", id);
        }
        eventEntities.removeIf(event -> event.getId().equals(id));
        idGenerator.getAndDecrement();
    }

    @Override
    public PageResponse<EventResponse> findAllPaginated(EventFilterRequest filter) {
        return null;
    }


}
